### ISSUE TITLE
Smarty 3.1.29 property 'sub_template' does not exist

### ISSUE THREAD

**Issue by fulopattila122** [fulopattila122/smarty3-include-if-exists#2]
Originally reported by @masimao

> This week i updated my Smarty from 3.1.27 to 3.1.29, then i am having a issue with the plugin, it is best described [at this link](https://github.com/smarty-php/smarty/issues/216) in GitHub.
> 
> I will be glad if you take a look and tell if is easy to solve the problem.

**Comment by fulopattila122** [comment]
The `getSubTemplate` method has either been removed or became private. I added my comments to the linked thread. It seems that  `_subTemplateRender()` needs to be used instead. I'll make some tests and update the plugin if it resolves the issue.

**Comment by mazzucode** [comment]
Thanks! I will be here if i can help.

**Comment by mazzucode** [comment]
Hi Attila,

Did you find some way to solve the issue?

Thanks!

**Comment by uwetews** [comment]
yes new function is _subTemplateRender()

**Comment by mazzucode** [comment]
Hi Attila,

Will you create a new release?

**Comment by fulopattila122** [comment]
Yes, will do it shortly

**Comment by fulopattila122** [comment]
Resolved as of v1.0.1

**Comment by mazzucode** [comment]
@fulopattila122 Thanks for your attention! If i can help, please tell me.

**Comment by uwetews** [comment]
@masimao You updated the file with the wrong method name. It must be '_subTemplateRender()'.
You missed the leading underscore.
@fulopattila122 Your update was correct.

**Comment by mazzucode** [comment]
@fulopattila122 https://github.com/fulopattila122, I downloaded the file
from your repository.

**Comment by uwetews** [comment]
@masimao after the download you must manually delete all compiled and cached templates.
did you that?

**Comment by uwetews** [comment]
Ah , got it.  
The method name '_subTemplateRender()' is correct for the Smarty master branch and the upcomming 3.1.30 version but not for 3.1.29

For 3.1.29 it must be

``` php
""\t\t echo \$_smarty_tpl->smarty->ext->_subtemplate->render(\$_smarty_tpl, " . $include_else                   . ", $_cache_id, $_compile_id, $_caching, $_cache_lifetime, $_vars, $_parent_scope);
```

@masimao As 3.1.29 does have a couple of problems I would not upgrade to 3.1.29 but the dev-master version until 3.1.30 gets released

**Comment by mazzucode** [comment]
@uwetews , Thanks for the tip! I will wait for 3.1.30 version.

**Comment by uwetews** [comment]
I like this plugin.
I provided a pull request with a complete rewrite of the plugin which should solve all problems.
- make it compatible with all Smarty 3.1 versions
- support all {include} attributes and option flags
- make it independent from {include} compiler internals and changes
- support relative template filepath

**Comment by fulopattila122** [comment]
v1.1.0 fixes this properly, credit goes to Uwe!

**Comment by mazzucode** [comment]
Great @uwetews! Many thanks! This plugin is very important in my application!

**Comment by mazzucode** [comment]
@uwetews , I updated Smarty to 3.1.29 and the plugin file too, but i received this error:

`Parse error: syntax error, unexpected '}' in /home/imobevodev/views_c/153d2837d046e1fd7f57cdd234e92826381df399_0.file.mounter.tpl.php on line 475`

Then i changed some lines in the plugin source code, they are:

Line 83 from:

```
            $output .= "}\n}\n?>\n";
```

To:

```
            $output .= "}\n?>\n";
```

And line 88 from:

```
        $output .= "}\n}\n?>\n";
```

To:

```
        $output .= "}\n?>\n";
```

Now Smarty is running fine. Could you please confirm if this changes are okay?

Thanks!
